version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    ignore:
      - dependency-name: "playwright"
      - dependency-name: "@material/*"
    open-pull-requests-limit: 10
    versioning-strategy: increase
