language: node_js
os: osx
osx_image: xcode11.4
node_js: lts/*
cache:
  directories:
    - node_modules
script:
  - defaults write org.chromium.Chromium NSAppSleepDisabled -bool YES
  - travis_retry travis_wait 30 npm test

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./dist
  on:
    branch: master
