language: node_js
node_js: lts/*

os: linux
dist: bionic
addons:
  apt:
    packages:
      # These are required to run webkit
      - libwoff1
      - libopus0
      - libwebp6
      - libwebpdemux2
      - libenchant1c2a
      - libgudev-1.0-0
      - libsecret-1-0
      - libhyphen0
      - libgdk-pixbuf2.0-0
      - libegl1
      - libgles2
      - libevent-2.1-6
      - libnotify4
      - libxslt1.1
      - libvpx5
      # This is required to run chromium
      - libgbm1
    # Upload snapshots
    # paths:
    #   - ./test/e2e/__image_snapshots__/Travis_macOS

jobs:
  include:
    - name: Unit Tests
      script: travis_retry npm test unit
    - name: E2E Chromium Desktop
      script: travis_retry npm test e2e
      env:
        - BROWSER=chromium
        - DEVICE=desktop
    - name: E2E Chromium Mobile
      script: travis_retry npm test e2e
      env:
        - BROWSER=chromium
        - DEVICE=mobile
    - name: E2E Firefox Desktop
      script: travis_retry npm test e2e
      env:
        - BROWSER=firefox
        - DEVICE=desktop
    - name: E2E Firefox Mobile
      script: travis_retry npm test e2e
      env:
        - BROWSER=firefox
        - DEVICE=mobile
    - name: E2E Webkit Desktop
      script: travis_retry npm test e2e
      env:
        - BROWSER=webkit
        - DEVICE=desktop
    - name: E2E Webkit Mobile
      script: travis_retry npm test e2e
      env:
        - BROWSER=webkit
        - DEVICE=mobile

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./dist
  on:
    branch: master
