language: node_js
node_js: lts/*

os: linux
dist: bionic
addons:
  apt:
    update: true
    packages:
      # Chromium dependencies
      - libnss3
      - libxss1
      - libasound2
      # Firefox dependencies
      - libdbus-glib-1-2
      - libxt6
    # Upload snapshots
  artifacts:
    paths:
      - ./test/e2e/__image_snapshots__/

jobs:
  include:
    # - name: Unit Tests
    #   script: travis_retry npm test unit
    # - name: E2E Chromium Desktop
    #   script: travis_retry npm test e2e
    #   env:
    #     - BROWSER=chromium
    #     - DEVICE=desktop
    # - name: E2E Chromium Mobile
    #   script: travis_retry npm test e2e
    #   env:
    #     - BROWSER=chromium
    #     - DEVICE=mobile
    # - name: E2E Firefox Desktop
    #   script: travis_retry npm test e2e
    #   env:
    #     - BROWSER=firefox
    #     - DEVICE=desktop
    # - name: E2E Firefox Mobile
    #   script: travis_retry npm test e2e
    #   env:
    #     - BROWSER=firefox
    #     - DEVICE=mobile
    - name: E2E Webkit Desktop
      os: osx
      osx_image: xcode11.5
      before_script:
        - defaults write org.webkit.Playwright AppleFontSmoothing -int 3
        - defaults write org.webkit.Playwright CGFontRenderingFontSmoothingDisabled -bool NO
      script: travis_retry npm test e2e
      env:
        - BROWSER=webkit
        - DEVICE=desktop
    - name: E2E Webkit Mobile
      os: osx
      osx_image: xcode11.5
      before_script:
        - defaults write org.webkit.Playwright AppleFontSmoothing -int 3
        - defaults write org.webkit.Playwright CGFontRenderingFontSmoothingDisabled -bool NO
      script: travis_retry npm test e2e
      env:
        - BROWSER=webkit
        - DEVICE=mobile

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./dist
  on:
    branch: master
