name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
      - name: Build for production
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  unit_tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
      - name: Run unit tests
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm test unit

  e2e_tests_ubuntu:
    needs: build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        browser: [chromium, firefox]
        device: [desktop, mobile]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x
      - uses: microsoft/playwright-github-action@v1
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Run e2e tests ${{ matrix.browser }} ${{ matrix.device }}
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm test e2e
        env:
          BROWSER: ${{ matrix.browser }}
          DEVICE: ${{ matrix.device }}
          TEST_WITH_DIST: true

  e2e_tests_macos:
    needs: build
    runs-on: macOS-10.15
    strategy:
      matrix:
        browser: [webkit]
        device: [desktop, mobile]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.x
      - uses: microsoft/playwright-github-action@v1
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Run e2e tests ${{ matrix.browser }} ${{ matrix.device }}
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm test e2e
        env:
          BROWSER: ${{ matrix.browser }}
          DEVICE: ${{ matrix.device }}
          TEST_WITH_DIST: true
      # - name: Upload Screenshots
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: ci_darwin
      #     path: ./test/e2e/__image_snapshots__/ci_darwin

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [build, unit_tests, e2e_tests_ubuntu, e2e_tests_macos]
    runs-on: ubuntu-18.04
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  deploy_preview:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy preview to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
